
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-svc  # Unique key of the Service
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue                # In the Pod, check Label
    release: "0"               # and check the release 

  ports:
    - name: http  # accept the traffic sent to port 80
      port: 8081
      nodePort: 30010  # best practise

  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-queue
  labels:
    app: queue
    release: "0"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
    ports:
      - containerPort: 8161
