name: DeployLambdaFn

on:
  workflow_dispatch:
  # push:
  #   - DeployLambda/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # setup py
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'


    - name: Install Gradio
      run: python -m pip install -r requirements.txt.cpu