name: GradiDeploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # setup py
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Gradio
      run: python -m pip install -r requirements.txt.cpu

    - name: Log in to Hugging Face
      run: python -c 'import huggingface_hub; huggingface_hub.login(token="${{ secrets.hf_token }}")'

    - name: Deploy to Spaces
      run: make deploy
