_target_: "src.backend.torch_local.models.mvegfruits.LitVegFruitsModel"


# dims: 
#   - 3
#   - 6
#   - 12
#   - 18
  
# depths: 
#   - 1
#   - 1
#   - 1
#   - 1
# head_fn: 'default'
# conv_ratio: 1.
# in_chans: 3
num_classes: 63


# pretrained: false  # always 
# model_name: 'Mamba'   # stick to mamba based models
lr: 1e-3
weight_decay: 1e-5